// Code generated by quasar. DO NOT EDIT.
package escrow

import (
	"encoding/binary"
	"bytes"

	solana "github.com/gagliardetto/solana-go"
)

var ProgramID = solana.MustPublicKeyFromBase58("22222222222222222222222222222222222222222222")

var MakeDiscriminator = [1]byte{0x00}
var TakeDiscriminator = [1]byte{0x01}
var RefundDiscriminator = [1]byte{0x02}

var EscrowAccountDiscriminator = [1]byte{0x01}

var MakeEventEventDiscriminator = [1]byte{0x00}
var TakeEventEventDiscriminator = [1]byte{0x01}
var RefundEventEventDiscriminator = [1]byte{0x02}

type Escrow struct {
	Maker solana.PublicKey
	MintA solana.PublicKey
	MintB solana.PublicKey
	MakerTaB solana.PublicKey
	Receive uint64
	Bump uint8
}

func DecodeEscrow(data []byte) *Escrow {
	offset := 0
	var maker solana.PublicKey
	copy(maker[:], data[offset:offset+32])
	offset += 32
	var mintA solana.PublicKey
	copy(mintA[:], data[offset:offset+32])
	offset += 32
	var mintB solana.PublicKey
	copy(mintB[:], data[offset:offset+32])
	offset += 32
	var makerTaB solana.PublicKey
	copy(makerTaB[:], data[offset:offset+32])
	offset += 32
	receive := binary.LittleEndian.Uint64(data[offset:])
	offset += 8
	bump := data[offset]
	offset += 1
	return &Escrow {
		Maker: maker,
		MintA: mintA,
		MintB: mintB,
		MakerTaB: makerTaB,
		Receive: receive,
		Bump: bump,
	}
}

type MakeEvent struct {
	Escrow solana.PublicKey
	Maker solana.PublicKey
	MintA solana.PublicKey
	MintB solana.PublicKey
	Deposit uint64
	Receive uint64
}

func DecodeMakeEvent(data []byte) *MakeEvent {
	offset := 0
	var escrow solana.PublicKey
	copy(escrow[:], data[offset:offset+32])
	offset += 32
	var maker solana.PublicKey
	copy(maker[:], data[offset:offset+32])
	offset += 32
	var mintA solana.PublicKey
	copy(mintA[:], data[offset:offset+32])
	offset += 32
	var mintB solana.PublicKey
	copy(mintB[:], data[offset:offset+32])
	offset += 32
	deposit := binary.LittleEndian.Uint64(data[offset:])
	offset += 8
	receive := binary.LittleEndian.Uint64(data[offset:])
	offset += 8
	return &MakeEvent {
		Escrow: escrow,
		Maker: maker,
		MintA: mintA,
		MintB: mintB,
		Deposit: deposit,
		Receive: receive,
	}
}

type TakeEvent struct {
	Escrow solana.PublicKey
}

func DecodeTakeEvent(data []byte) *TakeEvent {
	offset := 0
	var escrow solana.PublicKey
	copy(escrow[:], data[offset:offset+32])
	offset += 32
	return &TakeEvent {
		Escrow: escrow,
	}
}

type RefundEvent struct {
	Escrow solana.PublicKey
}

func DecodeRefundEvent(data []byte) *RefundEvent {
	offset := 0
	var escrow solana.PublicKey
	copy(escrow[:], data[offset:offset+32])
	offset += 32
	return &RefundEvent {
		Escrow: escrow,
	}
}

type MakeInput struct {
	Maker solana.PublicKey
	MintA solana.PublicKey
	MintB solana.PublicKey
	MakerTaA solana.PublicKey
	MakerTaB solana.PublicKey
	VaultTaA solana.PublicKey
	Deposit uint64
	Receive uint64
}

func NewMakeInstruction(input *MakeInput) *solana.GenericInstruction {
	accounts := []*solana.AccountMeta{
		solana.Meta(input.Maker).WRITE().SIGNER(),
		solana.Meta(func() solana.PublicKey { addr, _, err := solana.FindProgramAddress([][]byte{[]byte{0x65, 0x73, 0x63, 0x72, 0x6f, 0x77}, input.Maker[:]}, ProgramID); if err != nil { panic(err) }; return addr }()).WRITE(),
		solana.Meta(input.MintA),
		solana.Meta(input.MintB),
		solana.Meta(input.MakerTaA).WRITE(),
		solana.Meta(input.MakerTaB).WRITE(),
		solana.Meta(input.VaultTaA).WRITE(),
		solana.Meta(solana.MustPublicKeyFromBase58("SysvarRent111111111111111111111111111111111")),
		solana.Meta(solana.MustPublicKeyFromBase58("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")),
		solana.Meta(solana.MustPublicKeyFromBase58("11111111111111111111111111111111")),
	}
	data := make([]byte, 0, 256)
	data = append(data, MakeDiscriminator[:]...)
	{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], input.Deposit); data = append(data, buf[:]...) }
	{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], input.Receive); data = append(data, buf[:]...) }
	return solana.NewInstruction(ProgramID, accounts, data)
}

type TakeInput struct {
	Taker solana.PublicKey
	Maker solana.PublicKey
	MintA solana.PublicKey
	MintB solana.PublicKey
	TakerTaA solana.PublicKey
	TakerTaB solana.PublicKey
	MakerTaB solana.PublicKey
	VaultTaA solana.PublicKey
}

func NewTakeInstruction(input *TakeInput) *solana.GenericInstruction {
	accounts := []*solana.AccountMeta{
		solana.Meta(input.Taker).WRITE().SIGNER(),
		solana.Meta(func() solana.PublicKey { addr, _, err := solana.FindProgramAddress([][]byte{[]byte{0x65, 0x73, 0x63, 0x72, 0x6f, 0x77}, input.Maker[:]}, ProgramID); if err != nil { panic(err) }; return addr }()).WRITE(),
		solana.Meta(input.Maker).WRITE(),
		solana.Meta(input.MintA),
		solana.Meta(input.MintB),
		solana.Meta(input.TakerTaA).WRITE(),
		solana.Meta(input.TakerTaB).WRITE(),
		solana.Meta(input.MakerTaB).WRITE(),
		solana.Meta(input.VaultTaA).WRITE(),
		solana.Meta(solana.MustPublicKeyFromBase58("SysvarRent111111111111111111111111111111111")),
		solana.Meta(solana.MustPublicKeyFromBase58("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")),
		solana.Meta(solana.MustPublicKeyFromBase58("11111111111111111111111111111111")),
	}
	data := TakeDiscriminator[:]
	return solana.NewInstruction(ProgramID, accounts, data)
}

type RefundInput struct {
	Maker solana.PublicKey
	MintA solana.PublicKey
	MakerTaA solana.PublicKey
	VaultTaA solana.PublicKey
}

func NewRefundInstruction(input *RefundInput) *solana.GenericInstruction {
	accounts := []*solana.AccountMeta{
		solana.Meta(input.Maker).WRITE().SIGNER(),
		solana.Meta(func() solana.PublicKey { addr, _, err := solana.FindProgramAddress([][]byte{[]byte{0x65, 0x73, 0x63, 0x72, 0x6f, 0x77}, input.Maker[:]}, ProgramID); if err != nil { panic(err) }; return addr }()).WRITE(),
		solana.Meta(input.MintA),
		solana.Meta(input.MakerTaA).WRITE(),
		solana.Meta(input.VaultTaA).WRITE(),
		solana.Meta(solana.MustPublicKeyFromBase58("SysvarRent111111111111111111111111111111111")),
		solana.Meta(solana.MustPublicKeyFromBase58("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")),
		solana.Meta(solana.MustPublicKeyFromBase58("11111111111111111111111111111111")),
	}
	data := RefundDiscriminator[:]
	return solana.NewInstruction(ProgramID, accounts, data)
}

type DecodedEvent struct {
	Name string
	Data interface{}
}

func DecodeEvent(data []byte) *DecodedEvent {
	if len(data) >= 1 && bytes.Equal(data[:1], MakeEventEventDiscriminator[:]) {
		return &DecodedEvent{Name: "MakeEvent", Data: DecodeMakeEvent(data[1:])}
	}
	if len(data) >= 1 && bytes.Equal(data[:1], TakeEventEventDiscriminator[:]) {
		return &DecodedEvent{Name: "TakeEvent", Data: DecodeTakeEvent(data[1:])}
	}
	if len(data) >= 1 && bytes.Equal(data[:1], RefundEventEventDiscriminator[:]) {
		return &DecodedEvent{Name: "RefundEvent", Data: DecodeRefundEvent(data[1:])}
	}
	return nil
}

